language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
install:
  - npm install

env:
  global:
    - NODE_ENV=test

before_script:
  - npm run build
  - psql -c 'create database wayfarer_test;' -U postgres
script:
  - npm test
after_success:
  - npm run coverage
